module.exports={
    //开发地址
    dev_url:"",
    //生产地址
    pro_url:"http://eplusview.com:8088",
    //mqtt
    mqttUrl:"ws://eplusview.com:1884",
    mqttAccount:{
        username:"loraserver",
        password:"jbl21513118"
    },
}